### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by EGGSYSMAN** [ruppysuppy/SmartsApp#2]
Hi there,

I've set the rules and indexes at Firestore Database. The same goes for the Storage part. But here's what I get.
![image](https://user-images.githubusercontent.com/39420876/162693874-67291c65-8007-4a82-90c4-d501e30ba958.png)

**Comment by ruppysuppy** [comment]
You possibly didn't start the backend (end to end key generator) & link it in the front end (https://github.com/ruppysuppy/SmartsApp/blob/master/web_app/src/store/actions/baseUrl.ts)

**Comment by EGGSYSMAN** [comment]
> You possibly didn't start the backend (end to end key generator) & link it in the front end (https://github.com/ruppysuppy/SmartsApp/blob/master/web_app/src/store/actions/baseUrl.ts)

Can you help me how can I start?

**Comment by EGGSYSMAN** [comment]
> You possibly didn't start the backend (end to end key generator) & link it in the front end (https://github.com/ruppysuppy/SmartsApp/blob/master/web_app/src/store/actions/baseUrl.ts)

I replaced it with my website link but nothing's changed.

**Comment by ruppysuppy** [comment]
Then please checkout the network tab in dev tools find out which resource results in the network error

**Comment by EGGSYSMAN** [comment]
> Then please checkout the network tab in dev tools find out which resource results in the network error

Where are the dev tools?

**Comment by ruppysuppy** [comment]
In your browser

**Comment by ruppysuppy** [comment]
Are you sure you followed the steps here? https://github.com/ruppysuppy/SmartsApp/tree/master/e2ee_key_gen_server

**Comment by EGGSYSMAN** [comment]
> In your browser

Yeah, I followed but I wanna use only web-app from firebase hosting.

**Comment by EGGSYSMAN** [comment]
> Are you sure you followed the steps here? https://github.com/ruppysuppy/SmartsApp/tree/master/e2ee_key_gen_server

Hey, are you there?

**Comment by ruppysuppy** [comment]
You are running 2/3 of the application (firebase & front-end). The backend service (key generation server) is not running. You need all 3. If you want to use only firebase, then deploy the server on firebase & link it up using the `baseUrl`

**Comment by EGGSYSMAN** [comment]
> You are running 2/3 of the application (firebase & front-end). The backend service (key generation server) is not running. You need all 3. If you want to use only firebase, then deploy the server on firebase & link it up using the `baseUrl`

You are right, but I don't know how can I do it?

**Comment by EGGSYSMAN** [comment]
> You are running 2/3 of the application (firebase & front-end). The backend service (key generation server) is not running. You need all 3. If you want to use only firebase, then deploy the server on firebase & link it up using the `baseUrl`

Oh, E2EE Key generator was like an API and I started it other server and linked it up using the `baseurl`. Thank you for your help.
